### ISSUE TITLE
Thank you & question

### ISSUE THREAD

**Issue by avsaponchik** [mikedeboer/soundcloud-player#13]
I just want to say thank you for this addon. This addon works just flawlessly.
And, can i ask, how can i make the hotkeys on my keyboard to work globally? (for example, when i'm in the game). Currently hotkeys only work when i have browser window activated
(sorry for my russki)

**Comment by mikedeboer** [comment]
Thanks!

I'm afraid that's something I can't support through an addon :(
For that to work I would need to develop a separate system tray application that captures and forwards media key presses globally.

**Comment by avsaponchik** [comment]
Sadly, but we have what we have. Thanks again for this great addon!
(and it's even open new soundcloud tab when i don't have it opened! :D)
