### ISSUE TITLE
Rename keys on Linux

### ISSUE THREAD

**Issue by orschiro** [mikedeboer/soundcloud-player#5]
Hi @mikedeboer,

Many thanks for your add-on!

I added version `0.8` to Firefox `34.0.5` on Arch Linux 64-bit.

A slight design flaw that I would like to report.

I am wondering whether the buttons could be renamed to just `Previous`, `Play`, and `Next` instead of `prev-button`, etc.

Screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/170947/5655199/85f64794-96cb-11e4-8a7a-7f65c335a90d.png)

Thankfully,

Robert

**Comment by mikedeboer** [comment]
I'm glad you like it! And indeed, this is a bug! It seems like there something very odd going on wrt to i18n here... I'll fix it asap. Thanks for reporting!

**Comment by orschiro** [comment]
Glad I could help and that you know how to fix it.

Thanks!

Robert

On 08.01.2015 10:40, Mike de Boer wrote:
>
> I'm glad you like it! And indeed, this is a bug! It seems like there 
> something very odd going on wrt to i18n here... I'll fix it asap. 
> Thanks for reporting!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mikedeboer/soundcloud-player/issues/5#issuecomment-69156346>.
>

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#OpenSource #Sufficiency
#ResourceEfficiency

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by orschiro** [comment]
Thanks for |v0.9|. Just tried it.

Unfortunately the issue still persists for me…

Robert

On 08.01.2015 10:59, Mike de Boer wrote:

> Closed #5 <https://github.com/mikedeboer/soundcloud-player/issues/5> 
> via f2e8eef 
> <https://github.com/mikedeboer/soundcloud-player/commit/f2e8eef0377dcf1043193904d119dccd2375a06f>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mikedeboer/soundcloud-player/issues/5#event-215804372>.
>
​

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#OpenSource #Sufficiency
#ResourceEfficiency

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by orschiro** [comment]
Ignore my last comment. Version 0.9 works perfectly in Firefox 35.

Thanks a lot! :)
